#!/usr/bin/env bash
#
# Install the Ammunity SENDER skill into OpenClaw, in one step.
#
# Run this ON THE HOST, from a clone of this repo:
#   git clone https://github.com/ARandomGuy9786/OpenclawSkill.git ammunity-openclaw-skill
#   cd ammunity-openclaw-skill
#   cp .env.example .env   # then fill in AMMUNITY_AGENT_ID / AMMUNITY_AGENT_KEY
#   bash install.sh
#
# What it does:
#   1. Ensures this clone has its dependencies + .env (the clone is the runtime home).
#   2. Registers SKILL.md with OpenClaw. On OpenClaw >= 2026.5.28 this uses the
#      MANAGED skills dir (~/.openclaw/skills) which SURVIVES `openclaw update`.
#      On older OpenClaw (whose `skills install` only accepts ClawHub slugs) it
#      falls back to the bundled package dir, which `openclaw update` WIPES.
#   3. Creates an `ammunity` command on PATH that runs the delegate CLI.
#
# The `ammunity` command points at THIS clone (via /usr/local/bin), so it always
# survives `openclaw update`. Only the SKILL.md manifest is at risk on older
# OpenClaw — re-run this installer after an update, or upgrade to 2026.5.28+.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
WRAPPER="${AMMUNITY_WRAPPER_PATH:-/usr/local/bin/ammunity}"
OPENCLAW="${OPENCLAW_BIN:-openclaw}"

# 1. Runtime home = this clone: dependencies + credentials.
if [ ! -d "$HERE/node_modules" ]; then
  echo "Installing dependencies..."
  ( cd "$HERE" && npm install --silent )
fi
if [ ! -f "$HERE/.env" ]; then
  echo "WARNING: no $HERE/.env found. Copy .env.example to .env and fill in"
  echo "         AMMUNITY_AGENT_ID / AMMUNITY_AGENT_KEY before delegating."
fi

# 2. Register the skill with OpenClaw.
if ! command -v "$OPENCLAW" >/dev/null 2>&1; then
  echo "ERROR: '$OPENCLAW' not found on PATH. Set OPENCLAW_BIN=/path/to/openclaw and re-run." >&2
  exit 1
fi
# Newer OpenClaw (>= 2026.5.28) can install a LOCAL skill dir into the managed
# skills dir (~/.openclaw/skills), which persists across `openclaw update`. We
# stage a CLEAN copy of just SKILL.md, because `openclaw skills install` runs a
# security scan that rejects directories containing shell-spawn code (e.g. the
# receiver's child_process use), and the skill only needs SKILL.md (it just tells
# the agent to run the `ammunity` command from step 3). We detect support via --global.
if "$OPENCLAW" skills install --help 2>&1 | grep -q -- "--global"; then
  STAGE="$(mktemp -d)"
  cp "$HERE/SKILL.md" "$STAGE/SKILL.md"
  echo "Installing the 'ammunity' skill into OpenClaw's managed skills dir (survives openclaw update)..."
  "$OPENCLAW" skills install "$STAGE" --as ammunity --global --force
  rm -rf "$STAGE"
  SKILL_LOC="managed dir (~/.openclaw/skills/ammunity) — survives openclaw update"
else
  SKILL_DIR="$(npm root -g)/openclaw/skills/ammunity"
  echo "NOTE: this OpenClaw is older; its 'skills install' only supports ClawHub slugs."
  echo "      Installing SKILL.md into the bundled dir: $SKILL_DIR"
  echo "      WARNING: 'openclaw update' will WIPE this. Re-run install.sh after an update,"
  echo "      or upgrade OpenClaw to 2026.5.28+ for a persistent (managed-dir) install."
  mkdir -p "$SKILL_DIR"
  cp "$HERE/SKILL.md" "$SKILL_DIR/SKILL.md"
  SKILL_LOC="bundled dir ($SKILL_DIR) — WILL be wiped by 'openclaw update'"
fi

# 3. Create the `ammunity` command on PATH, pointing at this clone's CLI.
#    /usr/local/bin is on the gateway's PATH whether it runs as a service or a
#    shell. Needs sudo to write there.
echo "Creating the 'ammunity' command at $WRAPPER (may prompt for sudo) ..."
SUDO=""
[ -w "$(dirname "$WRAPPER")" ] || SUDO="sudo"
$SUDO tee "$WRAPPER" >/dev/null <<EOF
#!/usr/bin/env bash
# Ammunity command (auto-generated by install.sh). Points at the clone.
# Known subcommands run as-is so \`ammunity answer ...\` / \`ammunity discover\`
# work; a bare \`ammunity "task"\` still defaults to delegate.
case "\$1" in
  delegate|answer|discover) exec node "$HERE/lib/index.js" "\$@" ;;
  *) exec node "$HERE/lib/index.js" delegate "\$@" ;;
esac
EOF
$SUDO chmod +x "$WRAPPER"

echo
echo "Done."
echo "  skill    : $SKILL_LOC"
echo "  command  : $WRAPPER  ->  node $HERE/lib/index.js delegate"
echo
echo "Test it:   ammunity \"Test\" \"Say hello in one short sentence.\""
echo "Then start a new chat (or reload the gateway) so OpenClaw re-reads the skill."
