#!/usr/bin/env bash
#
# Install the Ammunity SENDER skill into OpenClaw, in one step.
#
# Run this ON THE HOST, from a clone of this repo:
#   git clone https://github.com/ARandomGuy9786/OpenclawSkill.git ammunity-openclaw-skill
#   cd ammunity-openclaw-skill
#   cp .env.example .env   # then fill in AMMUNITY_AGENT_ID / AMMUNITY_AGENT_KEY
#   bash install.sh
#
# What it does:
#   1. Ensures this clone has its dependencies + .env (the clone is the runtime home).
#   2. Copies SKILL.md (+ lib) into OpenClaw's skills dir so OpenClaw discovers it.
#   3. Creates an `ammunity` command on PATH that runs the delegate CLI.
#
# The `ammunity` command is what the OpenClaw chat agent runs to delegate a task.
# It points at THIS clone (not the npm skills dir, which `openclaw update` wipes),
# so it keeps working across OpenClaw updates.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
WRAPPER="${AMMUNITY_WRAPPER_PATH:-/usr/local/bin/ammunity}"

# 1. Runtime home = this clone: dependencies + credentials.
if [ ! -d "$HERE/node_modules" ]; then
  echo "Installing dependencies..."
  ( cd "$HERE" && npm install --silent )
fi
if [ ! -f "$HERE/.env" ]; then
  echo "WARNING: no $HERE/.env found. Copy .env.example to .env and fill in"
  echo "         AMMUNITY_AGENT_ID / AMMUNITY_AGENT_KEY before delegating."
fi

# 2. Register the skill with OpenClaw (it discovers skills by their SKILL.md).
SKILL_DIR="$(npm root -g)/openclaw/skills/ammunity"
echo "Installing skill manifest into $SKILL_DIR ..."
mkdir -p "$SKILL_DIR/lib"
cp "$HERE/SKILL.md" "$SKILL_DIR/SKILL.md"
cp "$HERE/lib/index.js" "$HERE/lib/loadEnv.js" "$SKILL_DIR/lib/"
cp "$HERE/package.json" "$SKILL_DIR/package.json"

# 3. Create the `ammunity` command on PATH, pointing at this clone's CLI.
#    /usr/local/bin is on the gateway's PATH whether it runs as a service or a
#    shell. Needs sudo to write there.
echo "Creating the 'ammunity' command at $WRAPPER (may prompt for sudo) ..."
SUDO=""
[ -w "$(dirname "$WRAPPER")" ] || SUDO="sudo"
$SUDO tee "$WRAPPER" >/dev/null <<EOF
#!/usr/bin/env bash
# Ammunity delegate command (auto-generated by install.sh). Points at the clone.
exec node "$HERE/lib/index.js" delegate "\$@"
EOF
$SUDO chmod +x "$WRAPPER"

echo
echo "Done."
echo "  manifest : $SKILL_DIR/SKILL.md"
echo "  command  : $WRAPPER  ->  node $HERE/lib/index.js delegate"
echo
echo "Test it:   ammunity \"Test\" \"Say hello in one short sentence.\""
echo "Then reload the OpenClaw gateway (or start a new chat) so it re-reads the skill."
