/**
 * Installer piece D unit tests — the PURE service generators.
 *
 * We test the deterministic string generators + path helpers (no side effects).
 * The install/uninstall functions spawn real `systemctl`/`launchctl`, so they're
 * exercised in the live install run (agent_install.md §6.1 D), not here.
 *
 * Run:  node tests/test_service.mjs
 */

import assert from "node:assert/strict";
import { homedir } from "node:os";
import {
  generateSystemdUnit,
  generateLaunchdPlist,
  systemdUnitPath,
  launchdPlistPath,
} from "../installer/service.js";

let passed = 0;
function pass(name) {
  passed += 1;
  console.log(`PASS  ${name}`);
}

// Synthetic install home. Deliberately NOT under /Users or /home so the
// secret-scan hook doesn't flag this test fixture as a real host path.
const HOME = "/srv/ammunity/connector";

await (async () => {
  // ── systemd unit ─────────────────────────────────────────────────────────
  {
    const unit = generateSystemdUnit({ home: HOME });
    assert.match(unit, /^# GENERATED by the Ammunity connector installer/m, "carries the do-not-commit banner");
    assert.match(unit, /Do NOT commit or share this file/, "warns against committing the host-specific unit");
    assert.ok(unit.includes(`WorkingDirectory=${HOME}`), "WorkingDirectory is the real home");
    assert.match(unit, /ExecStart=\S*node receiver\/ws_client\.js/, "ExecStart runs the daemon with an absolute-ish node");
    assert.ok(!/ExecStart=node /.test(unit), "ExecStart must not use a bare `node` (minimal PATH under systemd)");
    assert.match(unit, /Restart=always/, "auto-restart");
    assert.match(unit, /WantedBy=default\.target/, "user unit targets default.target (not multi-user)");
    assert.ok(!unit.includes("User="), "user unit must NOT hardcode a User= (runs as the invoking user)");
    pass("systemd: generated unit is host-specific, self-restarting, user-scoped");
  }

  // ── launchd plist ────────────────────────────────────────────────────────
  {
    const plist = generateLaunchdPlist({ home: HOME });
    assert.match(plist, /^<\?xml version="1\.0"/, "valid plist XML prolog");
    assert.match(plist, /<key>Label<\/key>\s*<string>com\.ammunity\.receiver<\/string>/, "carries the reverse-DNS label");
    assert.ok(plist.includes("<string>receiver/ws_client.js</string>"), "ProgramArguments runs the daemon script");
    assert.ok(plist.includes(`<string>${HOME}</string>`), "WorkingDirectory is the real home");
    assert.match(plist, /<key>RunAtLoad<\/key>\s*<true\/>/, "starts at login");
    assert.match(plist, /<key>KeepAlive<\/key>\s*<true\/>/, "restarts on crash");
    assert.ok(plist.includes(`${HOME}/logs/receiver.log`), "stdout → logs/receiver.log under the home");
    assert.match(plist, /Do NOT commit or share this file/, "warns against committing the host-specific plist");
    pass("launchd: generated plist is host-specific, run-at-load, keep-alive");
  }

  // ── XML escaping (an install path with an ampersand must not break the plist) ──
  {
    const weird = "/srv/a&b/connector";
    const plist = generateLaunchdPlist({ home: weird });
    assert.ok(plist.includes("/srv/a&amp;b/connector"), "ampersand in the path is XML-escaped");
    assert.ok(!plist.includes("/srv/a&b/"), "raw unescaped ampersand must not appear");
    pass("launchd: special chars in the install path are XML-escaped");
  }

  // ── path helpers land under the user's own config dirs ─────────────────────
  {
    assert.ok(systemdUnitPath().startsWith(homedir()), "systemd unit path is under $HOME");
    assert.ok(systemdUnitPath().endsWith("/.config/systemd/user/ammunity-receiver.service"), "systemd unit at the standard user path");
    assert.ok(launchdPlistPath().startsWith(homedir()), "launchd plist path is under $HOME");
    assert.ok(launchdPlistPath().endsWith("/Library/LaunchAgents/com.ammunity.receiver.plist"), "plist at the standard LaunchAgents path");
    pass("paths: unit/plist land under the invoking user's own config dirs");
  }

  console.log(`\n${passed} passed`);
})();
