/**
 * Pieces B + C of the installer:
 *   B. Place the connector runtime in a STABLE home and install its deps.
 *      (`npx` runs from a throwaway temp dir, so a persistent daemon can't run
 *      in place — we copy the runtime to ~/.ammunity/connector and install there.)
 *   C. Write the isolated `.env` (chmod 600) from the collected answers.
 *
 * Security/adaptability (standing discipline): the .env is the ONLY file that
 * holds secrets and it's never committed (chmod 600, under the user's home).
 * Nothing written here is hardcoded to a host — every path/value comes from the
 * running user or their answers.
 */

import { spawnSync } from "node:child_process";
import { chmodSync, cpSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// The installer's own package root (…/ammunity-connector), two levels up from
// installer/runtime.js. This is the source of the runtime files to copy.
export function packageRoot() {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..");
}

// Default stable home for the placed runtime. Overridable via --home / AMMUNITY_HOME.
export function defaultHome() {
  return process.env.AMMUNITY_HOME || join(homedir(), ".ammunity", "connector");
}

// Only the files the daemon (and the sender lib) actually need at runtime.
// Excludes .git, node_modules, .env, .DS_Store, the installer itself, and docs.
const RUNTIME_DIRS = ["receiver", "lib"];
const RUNTIME_FILES = [".env.example"];
const COPY_SKIP = new Set(["node_modules", ".git", ".env", ".DS_Store"]);

// B. Copy the runtime into `home` (idempotent; skips itself if already there).
export function placeRuntime(home, log = () => {}) {
  const src = packageRoot();
  const dest = resolve(home);
  if (src === dest) {
    log("already running from the install home — nothing to copy");
    return { copied: false, home: dest };
  }
  mkdirSync(dest, { recursive: true });
  for (const d of RUNTIME_DIRS) {
    const from = join(src, d);
    if (!existsSync(from)) continue;
    cpSync(from, join(dest, d), {
      recursive: true,
      filter: (p) => !COPY_SKIP.has(p.split(/[\\/]/).pop()),
    });
  }
  for (const f of RUNTIME_FILES) {
    const from = join(src, f);
    if (existsSync(from)) cpSync(from, join(dest, f));
  }
  // Generate a minimal runtime package.json (no installer bin/scripts → no
  // dangling-bin link on `npm install`; just the deps the daemon needs).
  writeFileSync(
    join(dest, "package.json"),
    JSON.stringify(
      {
        name: "ammunity-connector-runtime",
        version: "1.0.0",
        private: true,
        type: "module",
        dependencies: { "node-fetch": "^3.0.0", ws: "^8.18.0" },
      },
      null,
      2
    ) + "\n"
  );
  log(`placed runtime → ${dest}`);
  return { copied: true, home: dest };
}

// B (cont). Install deps in `home`. Non-fatal on failure (the user can re-run).
export function installDeps(home, log = () => {}) {
  log("installing dependencies (npm install)…");
  const res = spawnSync("npm", ["install", "--omit=dev", "--no-audit", "--no-fund"], {
    cwd: home,
    stdio: "inherit",
    shell: process.platform === "win32", // npm is a .cmd shim on Windows
  });
  if (res.status !== 0) {
    log("⚠ npm install did not complete cleanly — run it yourself in the install home before starting.");
    return false;
  }
  return true;
}

// C. Compose the `.env` body from answers. Only writes lines that are relevant
// to the chosen role/brain/auth, so the file stays minimal and readable.
export function composeEnv(answers) {
  const { role, brain, agentId, agentKey, coordinatorUrl, brainBin, claudeAuth, claudeApiKey } = answers;
  const lines = [
    "# Ammunity connector — credentials & config (generated by the installer).",
    "# This file holds secrets: it is chmod 600 and MUST NOT be committed.",
    "",
    `AMMUNITY_AGENT_ID=${agentId}`,
    `AMMUNITY_AGENT_KEY=${agentKey}`,
  ];
  // Only emit the coordinator URL when overridden (config.js defaults to prod).
  if (coordinatorUrl) lines.push(`AMMUNITY_COORDINATOR_URL=${coordinatorUrl}`);

  if (role === "receive" || role === "both") {
    lines.push("", `AMMUNITY_BRAIN=${brain}`);
    if (brain === "openclaw" && brainBin) {
      lines.push("# Absolute openclaw path (systemd/launchd run with a minimal PATH).", `OPENCLAW_BIN=${brainBin}`);
    }
    if (brain === "claude") {
      if (brainBin) lines.push(`CLAUDE_BIN=${brainBin}`);
      if (claudeAuth === "login") {
        lines.push("# Reuse the user's existing ~/.claude login (free; shares the personal home).", "AMMUNITY_CLAUDE_USE_LOGIN=1");
      } else if (claudeAuth === "apikey" && claudeApiKey) {
        lines.push("# Isolated home + API key (per-token billing).", `ANTHROPIC_API_KEY=${claudeApiKey}`);
      }
    }
  }
  return lines.join("\n") + "\n";
}

// C (cont). Write `.env` to `home` with 0600 perms. Returns the path.
export function writeEnv(home, answers, log = () => {}) {
  const envPath = join(home, ".env");
  writeFileSync(envPath, composeEnv(answers), { mode: 0o600 });
  try {
    chmodSync(envPath, 0o600); // re-assert (umask can widen the create mode)
  } catch {
    /* best-effort on platforms without POSIX perms (Windows) */
  }
  log(`wrote credentials → ${envPath} (chmod 600)`);
  return envPath;
}
