/**
 * Piece D of the installer: per-OS service generation.
 *
 * GENERATES a systemd user unit (Linux) or launchd LaunchAgent (macOS) from
 * the REAL host's user, home dir, and paths — never a personalized file in the
 * repo (the 2026-06-29 leak). Installs it, enables it, starts it, and verifies
 * it came up. `uninstallService` reverses all of it.
 *
 * Per-USER services (not system-wide), on purpose: launchd LaunchAgents are
 * inherently per-user (they run at login, with access to the user's own
 * ~/.claude login for the Claude brain) — a LaunchDaemon would run without a
 * user session and couldn't see it. `systemctl --user` mirrors that on Linux
 * so both OSes behave the same way and neither needs root. `loginctl
 * enable-linger` is the Linux equivalent of "start without an active login".
 *
 * Windows service generation is a fast-follow (NSSM / `sc` / Task Scheduler);
 * this module is a no-op on win32 (system.js already flags it unsupported).
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir, userInfo } from "node:os";
import { dirname, join } from "node:path";
import { which } from "./system.js";

const SYSTEMD_UNIT_NAME = "ammunity-receiver";
const LAUNCHD_LABEL = "com.ammunity.receiver";

export function systemdUnitPath() {
  return join(homedir(), ".config", "systemd", "user", `${SYSTEMD_UNIT_NAME}.service`);
}

export function launchdPlistPath() {
  return join(homedir(), "Library", "LaunchAgents", `${LAUNCHD_LABEL}.plist`);
}

// The absolute node path — service managers run with a minimal PATH, so a
// bare `node` in ExecStart/ProgramArguments would fail to resolve.
function nodeBin() {
  return which("node") || process.execPath;
}

function escapeXml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// ── generators (pure — no side effects, easy to unit-test) ─────────────────

export function generateSystemdUnit({ home }) {
  const node = nodeBin();
  return `# GENERATED by the Ammunity connector installer for this host.
# Do NOT commit or share this file — it is specific to this user/machine.
[Unit]
Description=Ammunity receiver daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${home}
ExecStart=${node} receiver/ws_client.js
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
`;
}

export function generateLaunchdPlist({ home }) {
  const node = nodeBin();
  const logDir = join(home, "logs");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- GENERATED by the Ammunity connector installer for this host.
     Do NOT commit or share this file — it is specific to this user/machine. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(node)}</string>
    <string>receiver/ws_client.js</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${escapeXml(home)}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${escapeXml(join(logDir, "receiver.log"))}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(join(logDir, "receiver.error.log"))}</string>
</dict>
</plist>
`;
}

// ── install/start/verify ─────────────────────────────────────────────────

// systemd --user needs XDG_RUNTIME_DIR; it's often unset over a plain SSH
// session (no login-session bus). Fill in the conventional path if missing.
function systemctlEnv() {
  const env = { ...process.env };
  if (!env.XDG_RUNTIME_DIR) env.XDG_RUNTIME_DIR = `/run/user/${userInfo().uid}`;
  return env;
}

// Returns { ok, installed, detail } — `ok` false means non-fatal (caller
// prints the manual-run fallback); `detail` is a short human-readable status.
export function installLinuxService(home, log = () => {}) {
  if (!which("systemctl")) {
    return { ok: false, installed: false, detail: "systemctl not found (no systemd on this host)." };
  }

  const unitPath = systemdUnitPath();
  mkdirSync(dirname(unitPath), { recursive: true });
  writeFileSync(unitPath, generateSystemdUnit({ home }));
  log(`generated systemd unit → ${unitPath}`);

  const env = systemctlEnv();
  const run = (args) => spawnSync("systemctl", ["--user", ...args], { env, encoding: "utf8" });

  run(["daemon-reload"]);
  const enableRes = run(["enable", "--now", SYSTEMD_UNIT_NAME]);
  if (enableRes.status !== 0) {
    return { ok: false, installed: true, detail: (enableRes.stderr || enableRes.stdout || "enable failed").trim() };
  }

  // Best-effort: without lingering, a `systemctl --user` service stops when
  // the user's last session ends (e.g. the SSH connection that ran the
  // installer closes). Not fatal if it fails (needs polkit/root on some
  // distros) — just warn so the user knows to ask an admin.
  const user = userInfo().username;
  const lingerRes = spawnSync("loginctl", ["enable-linger", user], { encoding: "utf8" });
  if (lingerRes.status !== 0) {
    log(
      `⚠ couldn't enable lingering for "${user}" (needs root/polkit) — the service may stop when you log ` +
        `out. Ask an admin to run: loginctl enable-linger ${user}`
    );
  }

  const status = run(["is-active", SYSTEMD_UNIT_NAME]);
  const active = (status.stdout || "").trim() === "active";
  return {
    ok: active,
    installed: true,
    detail: active ? "active" : (status.stdout || status.stderr || "not active").trim(),
  };
}

export function installMacService(home, log = () => {}) {
  if (!which("launchctl")) {
    return { ok: false, installed: false, detail: "launchctl not found." };
  }

  const plistPath = launchdPlistPath();
  mkdirSync(dirname(plistPath), { recursive: true });
  mkdirSync(join(home, "logs"), { recursive: true });
  writeFileSync(plistPath, generateLaunchdPlist({ home }));
  log(`generated launchd plist → ${plistPath}`);

  // Idempotent re-run: unload any previous copy first (ignore failure — it
  // may not have been loaded yet).
  spawnSync("launchctl", ["unload", plistPath], { encoding: "utf8" });
  const loadRes = spawnSync("launchctl", ["load", "-w", plistPath], { encoding: "utf8" });
  if (loadRes.status !== 0) {
    return { ok: false, installed: true, detail: (loadRes.stderr || loadRes.stdout || "load failed").trim() };
  }

  const list = spawnSync("launchctl", ["list", LAUNCHD_LABEL], { encoding: "utf8" });
  const running = list.status === 0;
  return { ok: running, installed: true, detail: running ? "loaded" : (list.stderr || list.stdout || "not listed").trim() };
}

// Dispatches on the running host's OS. Returns null on unsupported platforms
// (caller falls back to the manual `node receiver/ws_client.js` instructions).
export function installService(home, log = () => {}) {
  if (process.platform === "linux") return installLinuxService(home, log);
  if (process.platform === "darwin") return installMacService(home, log);
  return null;
}

// Reverses whichever service is present for this platform. Best-effort and
// silent about absence (uninstall may run on a send-only or never-serviced
// install).
export function uninstallService(log = () => {}) {
  if (process.platform === "linux") {
    const unitPath = systemdUnitPath();
    if (!existsSync(unitPath)) return;
    const env = systemctlEnv();
    spawnSync("systemctl", ["--user", "disable", "--now", SYSTEMD_UNIT_NAME], { env, encoding: "utf8" });
    rmSync(unitPath, { force: true });
    spawnSync("systemctl", ["--user", "daemon-reload"], { env, encoding: "utf8" });
    log(`removed systemd unit (${unitPath})`);
    return;
  }
  if (process.platform === "darwin") {
    const plistPath = launchdPlistPath();
    if (!existsSync(plistPath)) return;
    spawnSync("launchctl", ["unload", plistPath], { encoding: "utf8" });
    rmSync(plistPath, { force: true });
    log(`removed launchd plist (${plistPath})`);
  }
}
